github-organizations.yml
Adding a new organization
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/MicroFocus_CI_microfocus.github.io_idol
=> Adding microfocus-idol

src/app/shared/components/masthead/masthead.component.html
Change masthead icon to link to microfocus.com 
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/MicroFocus_CI_microfocus.github.io_masthead-link
=> Masthead link

projects.yml
improve project description for Octane Issues Reporter project
=> improve description for Octane Issues Reporter project

src/app/shared/components/footer/footer.component.html
Change the contact us link to an email address
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/MicroFocus_CI_microfocus.github.io_contact-us
=> Change target of Contact Us to mailto:

projects.yml
* [x ] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x ] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x ] The code in this PR does not contain export-restricted encryption algorithms.
https://portal.digitalsafe.net/browse/SCMOD-9179
=> SCMOD-9179: Add Swagger UI project

blog-posts/2020-04-30-Post-ElasticMappingUpdater.md, projects.yml
* [x ] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x ] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x ] The code in this PR does not contain export-restricted encryption algorithms.
https://portal.digitalsafe.net/browse/SCMOD-9180
=> SCMOD-9180: Adding elastic-mapping-updater project

blog-posts/2020-04-30-Post-ElasticMappingUpdater.md
* [x ] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x ] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [ x] The code in this PR does not contain export-restricted encryption algorithms.
Jira: https://portal.digitalsafe.net/browse/SCMOD-9180
=> SCMOD-9180: Update blog

github-organizations.yml
Add link to NetIQ Professionsl Services organization on github.
=> added NetIQ-PS organization

package-lock.json
=> US582211 Update eventsource version to 1.1.1

package-lock.json
=> US582211 Update lodash version to 4.17.21

package-lock.json
=> US582211 Update loader-utils version to 2.0.3

package-lock.json
=> US582211 Bump tar from 4.4.8 to 4.4.19

package-lock.json
=> US582211 Bump moment from 2.24.0 to 2.29.4

package-lock.json
=> US582211-Bump terser from 4.1.3 to 4.8.1

package-lock.json
=> US582211 Bump y18n from 3.2.1 to 3.2.2

package-lock.json
=> US582211 Bump acorn from 6.2.1 to 6.4.2

package-lock.json
=> US582211 Bump dns-packet from 1.3.1 to 1.3.4

package-lock.json
=> US582211 Bump http-proxy from 1.17.0 to 1.18.1

package-lock.json
=> US582211 Bump websocket-extensions from 0.1.3 to 0.1.4

package-lock.json
=> US582211 Bump loader-utils from 2.0.3 to 2.0.4

package-lock.json
=> US582211 Bump node-forge from 0.7.5 to 1.3.0

package-lock.json
=> US582211 Bump kind-of from 6.0.2 to 6.0.3

package-lock.json
=> US582211 Bump async from 2.6.2 to 2.6.4

package-lock.json
=> US582211 Bump copy-props from 2.0.4 to 2.0.5

projects.yml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=610010
=> US610010 Remove Octane Issues Reporter from projects.yml

README.md, pom.xml, projects.yml, release-notes-1.4.0.md, release-notes-2.0.0.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=728101
Release preperation
=> US728101: Release preparation
